### ISSUE TITLE
Round 2: Tables Missing from KP Reports

### ISSUE THREAD

**Issue by emilybacon** [UCCC/CHORDS-QA#111] opened 2021-03-23 17:54 UTC
There are a few tables that didn't populate in Kaiser's P1 and P2 reports. The missing P2 tables are more of a priority than the P1 table. Below is a list of the tables that did not populate. Let me know if you want me to attach the reports here or whether you have copies available.

Missing tables:

P2: 
Table 2
Table 4
Table 7
Figure 9b

P1:
Table 4.1

**Comment by CartWill** [comment] 2021-04-13 23:12
@emilybacon The reports don't give too much info about the root cause of the errors so I'm not sure how to fix them.  It looks like a number of dataframes just didn't get created.  Since we don't have the report stop on an error, we sometimes loose info about where an error occurred.  I updated some of the logging to be a little more robust.  It will provide some messages about when each code chunk executes and it's duration and log any SQL errors that occur.  If a SQL error occurs it should get put into the final output so it should help with the why something failed.  Also at Kaiser, Mark is working on trying to make the queries run faster by editing the underlying view code.  That should help if the reason why the queries fail is because they timeout.  I had put in a hard-coded timeout of 35 minutes for the queries that run with the "run_query" function.  I can expand that if we need to but I want to be mindful of monopolizing someone's server.  

The Datamart Client should also now try to scoop up the R log file and read it into it's own log after someone tries to run it from the client.

**Comment by emilybacon** [comment] 2021-04-14 15:03
@CartWill these sound like solid strategies to troubleshoot the issues and get more info about what may be causing them. Thank you for implementing them and working with Mark to improve KP's process. We meet with KP in 2 weeks to discuss their data. Do you think we should ask them to re-run P2 in the meantime using the new code or do you think we should wait until the next round of QA in the summer?

**Comment by CartWill** [comment] 2021-04-14 17:10
@emilybacon I think we could ask him to re-run but he's trying to run P3 right now.  If he can get a result created for that, I think we can ask him to re-run P2.

**Comment by CartWill** [comment] 2021-07-14 20:29
Closing for now till KP can try to re-run the report.  There's more error output in the QA reports now so hopefully that give more clues if it's still broken.

**Closed as completed by CartWill** 2021-07-14 20:29 UTC
